### ISSUE TITLE
Incompatible versions...

### ISSUE THREAD

**Issue by tajaouart** [chrisedg87/flutter_rounded_loading_button#15]
Max version that woks is the 1.0.4, but the recents do not.
```yaml
sdk: ">=2.7.0 <3.0.0"
.....
 rxdart:
    dependency: transitive
    description:
      name: rxdart
      url: "https://pub.dartlang.org"
    source: hosted
    version: "0.23.1"
```
The error Message :
```
Because no versions of select_dialog match >1.1.0 <2.0.0 and select_dialog 1.1.0 depends on rxdart ^0.23.1, select_dialog ^1.1.0 requires rxdart ^0.23.1.
And because rounded_loading_button >=1.0.5 depends on rxdart ^0.24.0, select_dialog ^1.1.0 is incompatible with rounded_loading_button >=1.0.5.
So, because my_civi_flutter_app depends on both select_dialog ^1.1.0 and rounded_loading_button ^1.0.5, version solving failed.
pub get failed (1; So, because my_civi_flutter_app depends on both select_dialog ^1.1.0 and rounded_loading_button ^1.0.5, version solving failed.)
```
